# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:

    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://github.com
    strategy:
      matrix:
        node-version: [14.x]
    env:
      mongoURI: ${{ secrets.MONGO_DB_URI }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: movie-api-dan
          heroku_email: "danielufeli@gmail.com"
          usedocker: true
          justlogin: true
          docker_build_args: |
            NODE_ENV
            SECRET_KEY
            mongoURI

        env:
          NODE_ENV: development
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          mongoURI: ${{ secrets.MONGO_DB_URI }}
      
      - run: |
         git config user.name "daniel ufeli" && git config user.email "danielufeli@yahoo.com"
         heroku git:remote -a movie-api-dan
         git push heroku-dev HEAD:dev